# Generated by Django 4.2 on 2023-04-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroClientes', '0002_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
