# Generated by Django 4.2 on 2023-04-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroClientes', '0004_cliente_estado_civil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
    ]
