# Generated by Django 4.2 on 2023-04-24 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroClientes', '0006_rename_profissoes_profissao_alter_profissao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CadastroClientes.profissao'),
        ),
    ]
