# Generated by Django 4.2 on 2023-04-25 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroClientes', '0008_remove_cliente_telefone_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='ddd',
            new_name='DDD',
        ),
    ]
