# Generated by Django 4.2 on 2023-04-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroClientes', '0009_rename_ddd_telefone_ddd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='interesses',
            field=models.ManyToManyField(to='CadastroClientes.interesse'),
        ),
    ]
